name: Deploy Odoo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .ssh directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Clean up conflicting packages
        run: |
          sudo apt remove -y moby-containerd moby-runc containerd runc

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      - name: Set up SSH keys
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.49.136.253 >> ~/.ssh/known_hosts

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 13.49.136.253
          username: ubuntu
          key: ${{ secrets.instance }}
          script: |
            # Run commands on the EC2 instance
            docker run -d -p 8069:8069 --name odoo --restart always -v /opt/odoo/data:/var/lib/odoo -v /opt/odoo/config:/etc/odoo -e POSTGRES_PASSWORD=youssoufa -e OE_SUPERADMIN_PASSWORD=youssoufa --link db:db --network bridge --expose 8069 odoo:latest
